### ISSUE TITLE
Feature Request: Can we also get span of matches found?

### ISSUE THREAD

**Issue by scarescrow** [vi3k6i5/flashtext#17] opened 2017-11-13 09:57 UTC
Most regex libraries also give the location of the matches found. Can this information also be provided by FlashText?

For example:
````
>>> from flashtext import KeywordProcessor
>>> keyword_processor = KeywordProcessor()
>>> # keyword_processor.add_keyword(<unclean name>, <standardised name>)
>>> keyword_processor.add_keyword('Big Apple', 'New York')
>>> keyword_processor.add_keyword('Bay Area')
# Maybe something like
>>> keywords_found = keyword_processor.extract_keywords('I love New York and Bay Area.', spanInfo=True)
>>> keywords_found
>>> # {'New York': (8,15), 'Bay Area': (21,28)}
````

**Comment by vi3k6i5** [comment] 2017-11-13 10:44
Duplicate of https://github.com/vi3k6i5/flashtext/issues/14

Merging and closing, will work on it soon.

**Closed by vi3k6i5** 2017-11-13 10:44 UTC
Labels: duplicate

**Comment by vi3k6i5** [comment] 2017-11-13 10:46
@scarescrow I will work on it soon. Thanks for validating the requirement of this feature.

**Comment by vi3k6i5** [comment] 2017-11-21 19:05
@scarescrow Not to bother you, but added the feature in Version 2.5

```
keyword_processor.extract_keywords('I love big Apple and Bay Area.', span_info=True)
# [('New York', 7, 16), ('Bay Area', 21, 29)]
```

**Comment by scarescrow** [comment] 2017-11-21 19:31
@vi3k6i5  Thanks!

**Comment by vi3k6i5** [comment] 2017-11-21 19:47
Hi, it's already an array of span so that is taken care of. I didn't go
with a dictionary for exactly this reason. Order is also preserved.

Thanks for pointing it out though.
